language: ruby
rvm:
  - ruby-head
  - 2.1.9
  - 2.2.5
  - 2.3.1
  - jruby-9.0.5.0
  - jruby-9.1.5.0

jdk:
  - oraclejdk8

before_install:
  - sh sudo add-apt-repository ppa:fontforge/fontforge; sudo apt-get update; sudo apt-get install fontforge
